GradientBoostingClassifier :
  n_estimators: 99
  learning_rate: 0.1
  max_depth: 4
  min_samples_leaf: 5
  max_features: 0.3

GradientBoostingRegressor:
  n_estimators: 200
  learning_rate: 0.05
  max_depth: 6
  min_samples_leaf: 5
  max_features: 0.3

RiskProfiles:
  claim_probability_thresholds:
    - 0.2
    - 0.45
  claim_amount_thresholds:
    - 0.2
    - 0.45
  weights_probability:
    Low: 0.4
    Medium: 0.5
    High: 0.6
  weights_cost:
    No Claim: 0.3
    Low: 0.4
    Medium: 0.5
    High: 0.6
  risk_score_thresholds:
    - 0.2
    - 0.45
